version: '3.8'

services:
  
  # backoffice-api:
  #   container_name: backoffice-api
  #   #image: rubemnascimento81/gym-app-prod:1.3
  #   build:
  #     context: "./backoffice-api"
  #     dockerfile: Dockerfile
  #     target: production
  #   command: npm run start:prod
  #   depends_on:
  #     - mysql
  #   ports:
  #     - 3000:3000
  #   environment:
  #   volumes:
  #     - ./backoffice-api:/usr/src/app
    

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gym_db
      - MYSQL_USER=rdn
      - MYSQL_ROOT_PASSWORD=rdn007
    volumes:
      - ./mysql_data:/var/lib/mysql