apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-api-api
  template:
    metadata:
      name: backoffice-api-api
      labels:
        app: backoffice-api-api
    spec:
      containers:
      - name: backoffice-api-api
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-api-service
spec:
  type: LoadBalancer
  selector:
    app: backoffice-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80