---
- name: Copy and Execute Script on Remote Host
  hosts: jenkins
  become: true
  tasks:
    - name: Copy docker.sh to remote host
      copy:
        src: docker-install.sh
        dest: /tmp/docker-install.sh
        mode: "0755"

    - name: Execute docker-install.sh on the remote host
      shell: /tmp/docker-install.sh && exit
      args:
        chdir: /tmp
      register: result

    - name: Check if the command succeeded
      debug:
        var: result.rc # Output the return code

    - name: Output stdout and stderr
      debug:
        msg:
          - "Stdout: {{ result.stdout }}"
          - "Stderr: {{ result.stderr }}"
