name: ci-workflow

on:
  push:
    branches:
      - branch-dev
  pull_request:
   types: [opened, synchronize, reopened]
  
  workflow_dispatch:

jobs:
  # config-scan:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     security-events: write # write permission on security tab
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: Run Trivy vulnerability scanner in IaC mode
  #       uses: aquasecurity/trivy-action@0.28.0
  #       with:
  #         scan-type: 'config'
  #         hide-progress: false
  #         format: "sarif"
  #         output: "trivy-config-results.sarif"
  #         exit-code: '0'
  #         ignore-unfixed: true
  #         severity: CRITICAL,HIGH,MEDIUM,LOW
      
  #     - name: Upload Trivy Scan Results to Github Security Tab
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: "trivy-config-results.sarif"
  
  #     - name: List files for debugging
  #       run: ls -al

  # check-application:
  #   needs: [config-scan]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"

  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: ./backoffice-api

  #     - name: Run end-to-end tests
  #       run: npm run test:e2e
  #       working-directory: ./backoffice-api
      
  #     - name: Run tests units
  #       run: npm run test:cov
  #       working-directory: ./backoffice-api

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #     - name: Build
  #       run: npm run build
  #       working-directory: ./backoffice-api

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./backoffice-api
  #         file: ./backoffice-api/Dockerfile
  #         push: true
  #         tags: |
  #           rubemnascimento81/gym-app:${{ github.sha }}
  #           rubemnascimento81/gym-app:latest

  image-scan:
    runs-on: ubuntu-latest
    #needs: [config-scan]
    permissions:
      security-events: write # write permission on security tab
    outputs:
      sarif-id: ${{ steps.upload-sarif.outputs.sarif-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: rubemnascimento81/gym-app:latest
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: 0
          severity: CRITICAL,HIGH,MEDIUM
      
      - name: Upload Trivy Scan Results to Github Security Tab
        id: upload-sarif  # Adiciona um ID a essa etapa
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Display SARIF ID
        run: echo "The SARIF ID is ${{ steps.upload-sarif.outputs.sarif-id }}"