name: Run End-to-End Tests

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The working directory for the tests.'
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
        db:
          image: mysql:8.0
          ports:
            - 3306:3306
          options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gym_db
            MYSQL_USER: rdn
            MYSQL_PASSWORD: rdn007

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      - name: Wait for DB to be ready
        run: |
          until mysqladmin ping -h"127.0.0.1" -u"rdn" -p"rdn007" --silent; do
            echo "Waiting for database connection..."
            sleep 2
          done

      - name: Run end-to-end tests
        run: npm run test:e2e
        working-directory: ${{ inputs.working-directory }}